# Generated by Django 4.0.5 on 2022-07-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
